### ISSUE TITLE
关于平台反爬机制的问题

### ISSUE THREAD

**Issue by zhangxliang** [obaby/baby_wx_post_spider#2]
你好，想问一下关于微信平台反爬机制，因为爬取到了一定的数量后，平台将会对账号进行一定的限制，比如爬取速度过快（2s一页）、数量过多（1000篇以上）后账号将不能查看每页的内容，想问一下作者对这方面的了解，以及对如何解决这类问题，谢谢。

**Comment by obaby** [comment]
多创建几个账号同时爬取，单账号爬取速度过快肯定会被封。如果要解决这个问题，可以通过自动更换爬取账号来解决。另外，如果说这种基于后台的操作效率太低影响速度的话，可以考虑通过mimproxy的方式，通过抓取客户端的web请求来解析公众号文章数据。整体来说实现爬虫的方式很多，但是各有利弊。这个还是要看自己的需求，多测试，然后选择一个合理的方式去爬取数据。
